command /feed [<player>]:
  permission: wsma.feed
  permission message: &cNo permission.
  trigger:
    arg 1 is not set:
      send "&bYou have to select an player."
      stop trigger
    arg 1 is set:
      arg 1 is not online:
        send "&bThis player is not online."
        stop trigger
    arg 1 is set:
      arg 1 is online:
        send "&bYou got feeded by %player%" to arg 1
        send "&b%arg 1% &bgot feeded."
        set food level of arg 1 to 20





every 1 second:
	loop all players:
		{reports.%loop-player's uuid%} is not set:
			set {reports.%loop-player's uuid%} to 0

on join:
	wait 1 tick
	create bossbar titled "&b&lWELCOME %PLAYER% &b&lTO WSMAFARMS!" and id "1" for player with progress 100 with colors blue
	wait 10 seconds
	remove bossbar "1"

on chat:
    if message contains "<3":
        if player has permission "donor.use" or "staff.use":
            replace all "<3" with "❤" in message
